apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgclass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageclassifier
  template:
    metadata:
      labels:
        app: imageclassifier
    spec:
      containers:
      - name: cv-app
        image: us-east4-docker.pkg.dev/vit-transformers-pytorch/vit/vit:v1
        ports:
        - containerPort: 8501
