name: Continuous Integration with Github Actions

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - name: Setup Kaggle
        run: |
          mkdir $HOME/.kaggle
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > $HOME/.kaggle/kaggle.json
          chmod 600 $HOME/.kaggle/kaggle.json

      - name: Download Dataset
        run: wget -P metadata/models/ https://huggingface.co/ubermenchh/vit_classification/raw/main/model.pth

      - name: Install dependencies
        run: |
          make install
          make run
